version: "3.2"

services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/addons
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
