version: 2
jobs:
 build_and_test:
   machine: true
   steps:
     - checkout
     - run:
        name: Pull Submodules
        command: |
          git submodule init
          git submodule update
     - run:
         name: Start docker
         command: make up
     - run:
         name: Run tests
         command: make test
     - store_test_results:
        path: /coverage/all
workflows:
 version: 2
 build_and_test:
   jobs:
     - build_and_test
