version: 2.1
orbs:
  deepsource: deepsource/test-coverage@1.1.0
jobs:
  build_and_test:
    machine: true
    # resource_class: monemasrl/odoo
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update
      - run:
          name: Start docker
          command: make up
      - run:
          name: Init DB
          command: make init_test_db
      - run:
          name: Run tests
          command: make generate_local_coverage_report
      - store_test_results:
          path: coverage/
      - deepsource/report:
          coverage-file: coverage/local/cov.xml
          dsn: "${DEEPSOURCE_DSN}"
          key: python
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
